version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: try_localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - AWS_REGION_NAME=us-east-1
      - AWS_ENDPOINT_URL=http://localhost:4566
      - AWS_ACCESS_KEY_ID=access_key
      - AWS_SECRET_ACCESS_KEY=secret_key
      - LOCAL_FILE_STORAGE_DIR=test_storage
    volumes:
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'