version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    env_file:
      - .env
    command: /entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    container_name: try_localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    env_file:
      - .env
    volumes:
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'