name: Run tests on any Push event
on:
  push:




jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Set ut Env
        with:
          BUCKETS: ${{secret.BUCKETS}}
          GOOGLE_APPLICATION_CREDENTIALS: ${{secret.GOOGLE_APPLICATION_CREDENTIALS}}
          run: echo ${{secret.GOOGLE_APPLICATION_CREDENTIALS}} > credentials.json
      - env:
          TEST_MODE: True
          BUCKETS: ${{secret.BUCKETS}}
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
          run: echo ${{secret.GOOGLE_APPLICATION_CREDENTIALS}} > credentials.json

      - name: Check out repository code
        uses: actions/checkout@v3.2.0

      - name: Install code dependency
        run: pip install -r requirements.txt

      - name: Run linters
        run: make lint

      - name: Run pytest
        run: make test