name: Run tests on any Push event
on:
  push:




jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.2.0

      - name: Install code dependency
        run: pip install -r requirements.txt

#      - name: Run linters
#        run: make lint

      - name: get dir
        run: pwd

      - name: Run pytest
        env:
          TEST_MODE: True
          BUCKETS: ${{ secrets.BUCKETS }}
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
          run: echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > ${{pwd}}/credentials.json
        run: make test