name: Run tests on any Push event
on:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-22.04
    environment: GCS
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.2.0

      - name: Install code dependency
        run: pip install -r requirements.txt

      - name: Run linters
        run: make lint

      - name: Prepare GCP auth
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > project-credentials.json

      - name: Create env file
        run: echo '${{ secrets.ENVS }}' > .env

      - name: Run pytest
        env:
          BUCKETS: ${{ secrets.BUCKETS }}
        run: make test